"""
Step 7 (final): PR Creator — create a GitHub pull request with the fix.
"""

from services.github_service import GitHubService


class PRCreator:
    """Creates a GitHub pull request with the generated fix."""

    def __init__(self, github_service: GitHubService):
        self.github = github_service

    async def create(
        self,
        repo_url: str,
        incident_id: str,
        ticket_data: dict,
        root_cause: dict,
        fix_data: dict,
        test_data: dict,
        sandbox_results: dict,
    ) -> dict:
        """Create a branch and PR with the fix and tests."""
        # Build branch name
        error_slug = (
            ticket_data.get("error_type", "fix")
            .lower()
            .replace(" ", "-")
            .replace("_", "-")[:30]
        )
        module_slug = (
            ticket_data.get("affected_module", "unknown")
            .replace("/", "-")
            .replace("_", "-")[:30]
        )
        branch_name = f"sentinel/{incident_id}-{error_slug}-{module_slug}"

        # Build PR body
        confidence = root_cause.get("confidence", 0)
        tests_passed = sandbox_results.get("tests_passed", 0)
        tests_failed = sandbox_results.get("tests_failed", 0)

        pr_body = f"""## 🤖 Sentinel Autonomous Fix

**Incident:** {ticket_data.get('summary', 'Unknown incident')}
**Error Type:** {ticket_data.get('error_type', 'Unknown')}
**Severity:** {ticket_data.get('severity', 'P2')}

---

### Root Cause Analysis
{root_cause.get('root_cause', 'Unknown')}

**Bug Pattern:** {root_cause.get('bug_pattern', 'Unknown')}
**Confidence:** {confidence}%

### Fix Description
{fix_data.get('fix_description', 'No description')}

**Strategy:** {fix_data.get('strategy', 'minimal-patch')}
**Risk Level:** {fix_data.get('risk_level', 'unknown')}

### Changes
```diff
{fix_data.get('diff', 'No diff available')}
```

### Test Results
- ✅ {tests_passed} tests passed
- ❌ {tests_failed} tests failed
- Tests generated: {test_data.get('test_count', 0)}

### Risk Assessment
{fix_data.get('risk_explanation', 'No risk assessment available')}

---
*This PR was autonomously generated by [Sentinel](https://github.com/vedishchawla/Sentinel) — an AI-powered incident-to-fix agent.*
"""

        pr_title = f"fix: {ticket_data.get('summary', 'autonomous fix')}"

        # Collect all files to commit
        files_to_update = {}

        # Add fixed source files
        for file_path, file_info in fix_data.get("files_to_modify", {}).items():
            if isinstance(file_info, dict) and "full_content" in file_info:
                files_to_update[file_path] = file_info["full_content"]

        # Add test file
        test_file = test_data.get("test_file_path")
        test_content = test_data.get("test_content")
        if test_file and test_content:
            files_to_update[test_file] = test_content

        if not files_to_update:
            return {
                "success": False,
                "error": "No files to commit",
                "pr_url": None,
                "pr_number": None,
                "branch": branch_name,
            }

        # Create PR via GitHub service
        result = await self.github.create_branch_and_pr(
            repo_url=repo_url,
            branch_name=branch_name,
            title=pr_title,
            body=pr_body,
            files_to_update=files_to_update,
        )

        result["branch"] = branch_name
        result["title"] = pr_title
        result["files_changed"] = len(files_to_update)

        return result
